services:
  fastapi:
    build: .
    ports:
      - "80:80"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017 
  mongodb:
    image: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
volumes:
  mongo_data: